- project:
    name: openstack/cookbook-openstack-application-catalog
    check:
      jobs:
        - openstack-chef-repo-rake:
            voting: false
        - openstack-chef-repo-integration:
            voting: false
